### ISSUE TITLE
Vulca tour

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#109]
## Pilsen
Todo List
- [x] mail to Bratislava
- [x] IRC Koblenz HAXKO
- [x] IRC Level2 Lux
- [x] IRC base48 brno

**Comment by nicolasdb** [comment]
Ashaffenburg
We discussed with Justin about how traveling can change the way we see things. We are lucky in Europe to have the facility to cross border and discover different cultures.
In US, they've not this. 

Erasmus should be world wide to help people connect

Erlangen
Alex told us about a congress in Berlin about what is the next wall we'll take down.
One of the talk was about borders. This concept is old and create more problems than solutions today. What about taking these walls down and be more citizens of the earth.

**Comment by nicolasdb** [comment]
Relab, link with enterprises, pme, students and peoples. Do workshops and is linked to an asbl. Mostly subsidized by public funding. 
Do escape room as teambuilding, boombox for kids. Can share what they do.
Lghs, much more underground, grassroot. Cool projects and lots of ideas on their wiki. For ex. Status asbl and governance.
And Aurelie portois.

**Comment by nicolasdb** [comment]
Fablab during the day, hackspace during the night. 
Fablab is linked yo university and the hackerspace is out, association.
Hackspace paid a membership to the ccc organisation which give insurance for every places member.
They have a vicky person :)

Fabuniverse Germany

Hasi. 
Again, a cool seiling with addressed led
Only guys ^^ heu geeks. 
But cool vibe. Hackespace is more about projects. They make and use stuff they need, or not. :)
They are kind of more engaged.

**Comment by nicolasdb** [comment]
![46202269_10218981845637873_6069982541048184832_o](https://user-images.githubusercontent.com/12049360/48669932-fb1f4480-eb0e-11e8-844d-cd43b8c9b16c.jpg)

**Comment by nicolasdb** [comment]
First part. 
BXL>Plzen 901km

![image](https://user-images.githubusercontent.com/12049360/48670267-42a8cf00-eb15-11e8-9aca-86dfdedb6a77.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/48969722-fbce4400-f002-11e8-92cb-e4a7a91764d3.png)

**Comment by AlexandreRousselet** [comment]
- [ ] Finaliser la fin du tour jour par jour
- [ ] Ecrire à Ondrej
- [ ] Ecrire à Grotlitz 
- [ ] Ecrire à Dresden
- [ ] Ecrire à Leipzig 
- [ ] Ecrire à Kassel 
- [ ] Ecrire à Marcel
- [ ] Ecrire à Koblenze 
- [ ] Trouver logement au Luxembourg

**Comment by nicolasdb** [comment]
yes, Top. 
J'ai contacté un autre pote au lux. un maker.

**Comment by nicolasdb** [comment]
shit, thanks to Microsoft, les drapeaux émoticone ne sont pas géré sous windows
Mais c'est certainement en cours... 

https://github.com/airbnb/javascript/issues/1789

**Comment by nicolasdb** [comment]
+10 labs
+768km

![image](https://user-images.githubusercontent.com/12049360/49935522-7cc97e80-fed1-11e8-9874-1108290b0a09.png)

**Comment by nicolasdb** [comment]
37 spaces
3971km + retour train Lux>Bxl

![image](https://user-images.githubusercontent.com/12049360/49936521-696be280-fed4-11e8-95af-7056d044d293.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/52786112-4687b700-305a-11e9-80a5-b97c2ac3d1d5.png)

**Comment by nicolasdb** [comment]
https://nicolasdb.github.io/post/vulcatour8/
