### ISSUE TITLE
post - 3Dprinter ANET E10 upgrade

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#16]
Upgrade de la nouvelle imprimante 3D.

Les problèmes à l'origine sont: 
- le transport merdique (comme d'hab, un effort est fait par les services postaux sur la délicatesse)
- matos chinois et faiblesse du pack et des finissions
  - alim DOA
  - courroies défaites
  - coup et griffe sur le bed à cause des vibrations/chocs
  - le support de lit est torché donc compensation avec les vis 
  - le chariot X est faible, 3 points seulement de contact, difficile à régler et donc jeu et imprécisions
  - moteurs Z mal orienté, nécessite une rotation de 90° pour déplacer le connecteur.
  - difficulté à régler les endstops pour Z et X

Bref, moultes optimisations possibles :D 

à commencer par 
- remplacer les roulements Y par des IGUS
- Ajouter des petits guides pour les ressorts du bed
- rotation des moteurs Z
- raccourcir le tube PTFE 
- bourriner avec une vis à bois le réglage du chariot X
- ventilo https://www.thingiverse.com/thing:2481362
- Z limit https://www.thingiverse.com/thing:2482030
- support PSU https://www.thingiverse.com/thing:2467824
- some foots to make place for electronics under. https://www.thingiverse.com/thing:2659913
- 2 filtres pour filament https://www.thingiverse.com/thing:1692395
- un boitier pour le fuse switch C14 https://www.thingiverse.com/thing:2119103
- un tendeur pour la courroie X https://www.thingiverse.com/thing:2589638

**Comment by nicolasdb** [comment]
Boitier à faire

![image](https://user-images.githubusercontent.com/12049360/34208040-18d38992-e58d-11e7-9a59-80b3c2960f51.png)

Liste cablage et prise. 
- Moteurs (2A 4Pin) x5, AWG?
- FAN (0.5A 2Pin) x2, AWG?
- BED (15A 2pin + 0.5A 2pin) AWG?
- hotend (5A 2pin + 0.5A 2pin) AWG?
- endstops (0.5A 2pin) AWG?

REcherche sur un module Logic Gate AND pour mettre 2 switch sur Z et faire un auto level mais c'est con. = plus de soucis et pas de prise en charge par la carte.

**Comment by nicolasdb** [comment]
un switch avec fuse s'appelle **C14 3 Pin Fused Power Socket**

**Comment by nicolasdb** [comment]
recup des pieds caoutchouc du boiter pour en dessous de la machine

![image](https://user-images.githubusercontent.com/12049360/34576995-19052b42-f180-11e7-9325-336407381621.png)

PSU placée en dessous, ça passe crème.
![image](https://user-images.githubusercontent.com/12049360/34577085-497d9228-f180-11e7-9f47-5db3390394e1.png)

et le controleur zoupla, sur un bout de rail DIN que j'avais dans mes caisses en attendant une meilleure solution.
![image](https://user-images.githubusercontent.com/12049360/34577129-6e231742-f180-11e7-8819-d296e8d2af26.png)

**Comment by nicolasdb** [comment]
next? 
connecter l'autoleveling
https://3dprint.wiki/reprap/anet/a8/improvement/autobedleveling

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/34579101-e513405a-f187-11e7-8cd5-0796ed44a43e.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/34786389-594a9080-f634-11e7-9e0f-e813f7345306.png)

![image](https://user-images.githubusercontent.com/12049360/34786394-5e1225c4-f634-11e7-875e-f20039106793.png)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/f6105e70-604b-48d6-a813-b0f08dde26e1)

![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/2b14043c-3285-44f8-8ba3-ab01ee308491)

![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/19a8dacc-32be-4f2b-8b46-b69e2d4e3564)

![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/fc7943cf-2d02-48b5-aa46-077302269e9b)

![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/8b4f7523-df7c-4d2d-a736-05dcae0172c4)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/65373525-1994-4bef-97be-ccc8b6f720b0)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/018ae3fb-5cf3-4cf2-be6f-f2f4647ab3d9)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/28aa6539-8c53-4c43-989a-fa99dd5ad3c5)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/14876a98-ae8f-4598-b055-df3428e38032)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/63547cf4-8831-4f4e-86a9-ec8a1664f24b)

**Comment by nicolasdb** [comment]
![image.png](https://images.zenhubusercontent.com/599be89f8f62dc7798c39c2f/96981e6c-c99f-41dd-a7f1-a6a23b7f0867)

**Comment by louistblm** [comment]
and for the 2fan wher do you put then
et pour les 2 ventilateur ou vous les avez mis

**Comment by nicolasdb** [comment]
Quels ventilateurs? 
sur l'extrudeur? ils restent au même endroit. comme sur les photos, non?

**Comment by podmore71** [comment]
I think Louistblm is referring to the 2 fans that were located in the control box. Doesn't the controller board or PSU get warm being situated under the heated bed? Just curious as I'm thinking of doing the same thing. I have printed legs to raise the unit up so that the controller box fits underneath, but I'd really like to get rid of it altogether if possible.

**Comment by nicolasdb** [comment]
ho, right. 
Well, I changed the power supply for a 30A with fan. The original one was DOA. 
And I added some heatsink on the controler board which is on the open now between the foots. So, plenty of air to cool down.
