### ISSUE TITLE
post - plan tarif fablab

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#27]
- [x] ref to file .md or pullRequest #: https://github.com/nicolasdb/nicolasdb.github.io/blob/master/_posts/2018-01-06-tarifs2018.md

@Valonlisbeth

**Fablab Brussels** 
Subventionné (ecole)
machine? 
>20€/h pour les laser rouge et 40€/h pour la laser grise

**Imal** 
Subventionné (feder? région?)
machine? Cyborg (ketele)
>15€/h pour laser
_Attention, les 15€/h, c'est uniquement pour compenser l'usure du tube laser. normalement, l'usage machine est gratuit (subvention)_
Formule pro (200€/an) et formule light (45€/mois)
(avec 10€ de réduction pour les workshop) http://imal.org/en/fablab/membership

**fablab ULB**
Subventionné (ecole)
machine? Cyborg (ketele)
>5€ min, 0,50€/min -> donc 30€/h
https://www.facebook.com/FabLabULB/app/256386574536637/

**Microfactory**
indépendant
machine? Cyborg (ketele)
?

**CityFab1**
Subventionné (Région)
machine? BCN?
? pas encore les machines je pense.

**fablab'ke**
Subventionné (CASTI)
machine: BCN
gratuit pour <18 ans (ou 16)

**Inkcut Lab**
PME sprl
machine: Trotek
J'ai entendu entre 100 et 120€/h

**Comment by nicolasdb** [comment]
Julien propose 50€/h et 10 à 15€ de prépa fichier.

**Comment by nicolasdb** [comment]
Du coup. 
Je pense monter à 40€/h. pour les membres.
La prépa fichier est de toutes façons le problème des membres. Sinon, ça passe dans le cadre "client" et le tarif de 55€/h. (ce qui s'approche de 40 + 15 de prépa fichier qui ne devrai pas prendre plus qu'1/4h)

Tarif client, la logique est la même donc. 40€/h pour l'usage machine + la main d'oeuvre à 55€/h
Est-ce que ça fait sens? 

L'ulb a un tarif minimum de démarrage. Est-ce que c'est pertinent dans le cas d'Openfab?

**Comment by Valonlisbeth** [comment]
de 10€ à 40€ d'un coup c'est pas un peu fort? tu offres d'autres services en accompagnement?

**Comment by nicolasdb** [comment]
non, 
mais faut que j'arrête de rêver et que les tarifs soit cohérent avec la réalité de ce que ça coute. 
à 10€, c'est moi qui paye les gens pour utiliser la machine. 

Par contre, une fois que le cout est fixé et cohérent, si tu (le membre) n'as pas les moyens financier, tu peux aider, participer et via la gamification, je serai ravi que tu gagne des crédits et que tu puisse t'acheter du tps machine avec. :D

**Comment by nicolasdb** [comment]
next step. 
**Comment comptabiliser le tps d'utilisation?**

J'aimerai aussi que le tps machine soit pré-payé. ce qui évite de devoir courir après les gens pour qu'il paye ce qu'ils doivent. 
La liste des conso laser est bien remplie mais il faut encore faire tout le suivit après. Et à 10€/h, personne n'est payé pour ça. 

Je vais donc ressortir les petites cartes à 10 encoches.
![image](https://user-images.githubusercontent.com/12049360/34641300-2d157564-f302-11e7-8b8f-ece3ba7108d6.png)

Le top serait de fabriquer une machine (un peu comme les timer électrique) qui s'activerai en insérant le disque et casserai les encoches toutes les x min. Reliée à un Relai pour activer la machine.

**Comment by Valonlisbeth** [comment]
C'est vrai qu'il faudra trouver un moyen de comptabiliser les temps au laser!
C'est juste que pour faire un bon aussi "important" il faut quand même pouvoir informer de façon préventive les anciens membres pour qu'ils puissent se préparer et peut être leur proposer en contre parti de plus s'impliquer via la gamification pour le début et le faire par étapes..? c'est une proposition

**Comment by nicolasdb** [comment]
J'ai écris un article sur le sujet, c'est déjà un élément d'explication.
Un autre élément d'explication.

Imal, les 15€/h, c'est uniquement pour compenser l'usure du tube laser. normalement,l'usage machine est gratuit (subvention)
