### ISSUE TITLE
post - Color code

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#29]
tag: openfab
@DewiBrunet

## White: 
universal background, to use with bleu, orange and red. 

![videoplayback 1 mp4_snapshot_03 07_ 2018 01 12_17 35 03](https://user-images.githubusercontent.com/12049360/34890862-d973feae-f7d3-11e7-95d0-4ebecf6760e4.jpg)
![videoplayback 1 mp4_snapshot_03 51_ 2018 01 12_17 37 36](https://user-images.githubusercontent.com/12049360/34890865-d9cafaf6-f7d3-11e7-8c58-3331a4caba39.jpg)

## Green Olive
Perfect to hide. 
Meaning as a background for Yellow or other texts. Sometimes with Red.

![videoplayback 1 mp4_snapshot_06 45_ 2018 01 12_17 38 32 - copy](https://user-images.githubusercontent.com/12049360/34890906-f741c330-f7d3-11e7-879e-057d5ea396db.jpg)
![videoplayback 1 mp4_snapshot_06 55_ 2018 01 12_17 38 37](https://user-images.githubusercontent.com/12049360/34890907-f7a15bb0-f7d3-11e7-9785-58f9b3897825.jpg)
![videoplayback 1 mp4_snapshot_04 49_ 2018 01 12_17 38 00 - copy](https://user-images.githubusercontent.com/12049360/34890908-f803dc68-f7d3-11e7-8661-75ebfc2f47f8.jpg)

## Yellow
To raise awareness. More than blue zone. 
Best used on Green Olive.

![videoplayback 1 mp4_snapshot_09 15_ 2018 01 12_17 40 50](https://user-images.githubusercontent.com/12049360/34890948-1904dde0-f7d4-11e7-80d8-722f334eeee1.jpg)

## Red
To use on things to use carefully. 
This color should not be use excessively. Only on small things, as a warning.

![videoplayback 1 mp4_snapshot_11 33_ 2018 01 12_17 45 20](https://user-images.githubusercontent.com/12049360/34890974-26b1c85e-f7d4-11e7-837c-524c477d47fe.jpg)
![videoplayback 1 mp4_snapshot_11 17_ 2018 01 12_17 45 01](https://user-images.githubusercontent.com/12049360/34890975-270ae81c-f7d4-11e7-9c05-160730ddfdcc.jpg)

## Blue
http://www.passetoncode.fr/panneaux-de-signalisation/panneaux/indication/
Blue as indication (square)/obligation (round). Could be for fixed storage or zone name, it's a guidance not a warning or interdiction.

![videoplayback 1 mp4_snapshot_14 58_ 2018 01 12_17 46 19](https://user-images.githubusercontent.com/12049360/34890988-33345ac4-f7d4-11e7-8a56-ad8220c6dad3.jpg)
![videoplayback 1 mp4_snapshot_15 28_ 2018 01 12_17 46 31](https://user-images.githubusercontent.com/12049360/34890990-33897130-f7d4-11e7-867c-46b721d47cd2.jpg)

## Orange
Could be to highlight things you can interact with. 
Like tools, switch, somethings you can move and/or afterward need to be put in place.

![videoplayback 1 mp4_snapshot_17 23_ 2018 01 12_20 00 11](https://user-images.githubusercontent.com/12049360/34891006-46d50ea2-f7d4-11e7-9d1e-908a759d8e9d.jpg)
![videoplayback 1 mp4_snapshot_18 05_ 2018 01 12_20 00 44](https://user-images.githubusercontent.com/12049360/34891007-472fe7dc-f7d4-11e7-9898-c030f54f2017.jpg)

## Black
Gloss for chalkboard, nice to show texture, easy to clean.
Mate for masking default on object or accept show the life of it.

![videoplayback 1 mp4_snapshot_20 28_ 2018 01 12_20 01 43](https://user-images.githubusercontent.com/12049360/34891028-5cfa1948-f7d4-11e7-96b8-ce983cfc47bc.jpg)
![videoplayback 1 mp4_snapshot_20 48_ 2018 01 12_20 02 02](https://user-images.githubusercontent.com/12049360/34891029-5d5198e4-f7d4-11e7-8719-768618994366.jpg)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/34891747-f38afd94-f7d6-11e7-8716-f3057c1eb4a3.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/34952683-d748aec4-fa1a-11e7-96c1-33848032beb6.png)

**Comment by DewiBrunet** [comment]
Pour le code de la route c'est intéressant de voir qu'il superpose un code couleur et un code de forme :
![47039662](https://user-images.githubusercontent.com/25649502/34955332-31d1c322-fa24-11e7-9941-9234870ab670.jpg)

**Comment by nicolasdb** [comment]
oui, exactement.
C'est bien ça. :)

**Comment by zuperninja** [comment]
Une face kaki et les côtés transparents ?

**Comment by nicolasdb** [comment]
oui, j'vais faire une maquette. 

Quand c'est rangé, on ne voit que la face avant. On garde la transparance des autres faces pour facilité l'identification des composants sans ouvrir la boite. 
Mais seulement lorsque tu tire la caisse. 

Le brol dedans, rend très difficile la lecture de ce que j'ai écrit, quelque soit la couleur du feutre. 
L'autre idée serait d'avoir des grands stickers à coller.

**Comment by nicolasdb** [comment]
Bon, j'ai pas trop passé de tps à ça mais voilà un exemple de base à affiner.
- Orange fluo sur le couvercle. idéalement, blanc + bande orange. = caisse à outils à ranger dans l'étagère orange correspondante.
- face visible "Olive green" mat, avec identification du contenu par catégorie (couleur) et sous-catégorie (texte)

![image](https://user-images.githubusercontent.com/12049360/34981476-e1250a0e-faa7-11e7-9f4b-1b529dc458f2.png)

**Comment by nicolasdb** [comment]
test
![colorcode](https://user-images.githubusercontent.com/12049360/35003264-991d95b0-faec-11e7-85a2-57172787392a.png)

**Comment by zuperninja** [comment]
J'aime beaucoup ! On peut garder les caisses qu'on a déjà et acheter des bombes de peintures kaki, orange, etc. Avec des poska correspondants pour écrire direct sur la peinture ? Quick&Dirty

**Comment by nicolasdb** [comment]
ouais, j'ai repensé aussi aux poska. 

On a tout réorganisé ce week-end avec @DewiBrunet et Camille. 
Dewi a fait des photos avant, après. (Dewi, tu peux en mettre quelques unes ici?)
J'ai laissé tourner la webcam aussi. Faudra récupérer les video et en faire un mini montage.

**Comment by DewiBrunet** [comment]
Voila un aperçu du nouvel aménagement :
![11](https://user-images.githubusercontent.com/25649502/35240935-3bba5124-ffb5-11e7-8e89-05539ad214c9.JPG)
![dsc05179](https://user-images.githubusercontent.com/25649502/35240936-3bd8e954-ffb5-11e7-89cf-12f7606ca320.JPG)
![dsc05196](https://user-images.githubusercontent.com/25649502/35240938-3c539c80-ffb5-11e7-82fc-28f7c82b4d4c.JPG)
![dsc05197](https://user-images.githubusercontent.com/25649502/35240939-3c741442-ffb5-11e7-9ad8-a183d7be2315.JPG)
![dsc05199](https://user-images.githubusercontent.com/25649502/35240940-3cdc188a-ffb5-11e7-954e-fafec70674e0.JPG)

**Comment by zuperninja** [comment]
AWESOME !!

**Comment by nicolasdb** [comment]
pour faire nos propres boites à la bonne dimension.
https://github.com/paulh-rnd/TabbedBoxMaker

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/36531179-58db3938-17bd-11e8-885b-9e5d4bc9b483.png)

![image](https://user-images.githubusercontent.com/12049360/36531563-9c1f2898-17be-11e8-9497-41fd2f986056.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/36532375-d81fe8c6-17c0-11e8-9ba5-a409438865b2.png)
