### ISSUE TITLE
Beer label

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#84]
## Openfab en stoemelings

Get Template from sam, 
We need, bear, beer and atome de faire.
The beer for bear from here. :)
ou 
- the beer from here for bears. 
- We beer bears.

**Comment by zuperninja** [comment]
![blason_ombre](https://user-images.githubusercontent.com/25099826/38406452-47b2aa68-3975-11e8-8da4-493b8314df89.png)

j'avais commencé ça aussi y a un moment

**Comment by nicolasdb** [comment]
yes, c'est sur le NAS. :+1:

**Comment by nicolasdb** [comment]
les étiquettes sont comme ça maintenant. 
![image](https://user-images.githubusercontent.com/12049360/38409813-2be582ac-3983-11e8-8708-21dc4ea0593a.png)
![image](https://user-images.githubusercontent.com/12049360/38409830-3c134574-3983-11e8-8f30-12f67302a3d0.png)

**Comment by nicolasdb** [comment]
Et on a déjà le design d'un petit bac 6bouteilles, pour les habitués. 

![image](https://user-images.githubusercontent.com/12049360/38732151-80d8cae0-3f1d-11e8-835c-8eabc787f9e3.png)

Et j'avais tenté des trucs moche avec l'atomium. J'aime bien l'atome de faire. 


![facityof](https://user-images.githubusercontent.com/12049360/38732251-d5595d96-3f1d-11e8-8ee4-dc39a2d577ac.png)

ici, avec un lien avec fabcity, leur logo est un truc avec des cubes de couleurs, ça fait 3D.  Assez basique.
![image4144](https://user-images.githubusercontent.com/12049360/38732256-d7e687c8-3f1d-11e8-8e67-76f2e1e0af41.png)

y a pas un super héro atomique? 

haha, si, Captain atom. 

![image](https://user-images.githubusercontent.com/12049360/38732363-2e43d850-3f1e-11e8-8252-a60e84282752.png)

![image](https://user-images.githubusercontent.com/12049360/38732442-73549bc8-3f1e-11e8-8cfc-255f765be00f.png)

**Comment by nicolasdb** [comment]
la brasserie de la senne a des cools étiquettes. 
http://brasseriedelasenne.be/?page_id=3885&lang=en

**Comment by nicolasdb** [comment]
ha tient, tant que j'y suis, j'ai retrouvé le lien vers le shop pour le swag de Roland
https://teespring.com/stores/rolands-bus-farm

**Comment by nicolasdb** [comment]
y a pas un super héro maker? 
Ouais, MacGyver :D 

![image](https://user-images.githubusercontent.com/12049360/38733083-f29658fc-3f20-11e8-974a-ee93b62463cf.png)

**Comment by zuperninja** [comment]
![capture d ecran 50](https://user-images.githubusercontent.com/25099826/38746805-e80b6738-3f48-11e8-972c-2264ace99185.png)

**Comment by nicolasdb** [comment]
y a une suite graphique aussi après l'étiquette. 
## the land of maker
issue #85

**Comment by nicolasdb** [comment]
idée pour la logique globale. 

Pour avoir une diversité visuelle, et donc permettre à différent illustrateur (rice) de passer par chez nous. 

Mettre des contraintes sur les symboles, et qu'openfab soit plus identifié par les symboles que par le style. = richesse des méthodes d'expressions sur base d'une éthique et de valeurs communes. 

**Ex:**
- l'ours, 
- l'atomium, 
- la diversité des membres, 
- la barbe, 
- le cyberpunk, Mmmm, ou DIY technologique quoi... 
- l'équilibre, l'écologie, écosystème. 
- à compléter....
\+ un minimum de charte graphique, pour la typo, le logo, et ce qu'on pense devoir être fixe.

**Comment by nicolasdb** [comment]
> et donc c'est 33.5€ la caisse, on imprime et on colle tout apd de 20 caisses normalement
> mais si vous voulez genre 10 caisses je veux bien offrir l'impression mais on vous prete notre etiquetteuse en bois pour les coller 😛
> et pour 5 caisses on vous file les bières avec les etiquettes eparees et on refacture l'impression ^^

**Comment by nicolasdb** [comment]
> concernant la binouzes de l'ours
> si jamais j'ai de la Tanteke non-étiauetée pour le moement
> vous avez donc les dimensions pour l'étiquette ?

**Comment by zuperninja** [comment]
Euh ? C'est leur message ça ? L'étiquette est prête de notre coté, faut juste mettre les bonnes infos (je crois qu'on a celle de la curieuseuneus seulement). Mais c'est la même taille que la leur

**Comment by nicolasdb** [comment]
Est-ce qu'on prend direct 20?

**Comment by zuperninja** [comment]
20 ça me parait bien !

**Comment by nicolasdb** [comment]
c'est commandé, 20 caisses. Je sais pas encore comment on va transporter tout ça :)

@zuperninja, Il faut finaliser le template. 
Il y a le nom et les ° de la bière. 
Puis je pense qu'il faut voir avec eux parce qu'il y a un numéro de lot et une date "best before..."

**Comment by zuperninja** [comment]
Tu peux leur demander le template de la tanteke du coup ? Et ils font livraison non ?

**Comment by nicolasdb** [comment]
bonne question. pour la livraison. on verra. 

le template tanteke, y a rien de différent, juste le txt et la couleur qui change un peu. 
![image](https://user-images.githubusercontent.com/12049360/38409830-3c134574-3983-11e8-8f30-12f67302a3d0.png)

**Comment by nicolasdb** [comment]
![enstoem](https://user-images.githubusercontent.com/12049360/50169510-015f3700-02ee-11e9-97dd-6f6efb522adc.jpg)
http://enstoemelings.be/

**Comment by nicolasdb** [comment]
![label](https://user-images.githubusercontent.com/12049360/50170078-5e0f2180-02ef-11e9-99a3-218becc8cae4.JPG)

**Comment by nicolasdb** [comment]
le post est en ligne,
